Make Substratum great again
nicholaschum/substratum pull request #105
Opened 2017-05-10 00:51 UTC by sirmordred

More robust

2017-05-10 20:13 UTC, sirmordred commented
Any review?

2017-05-10 21:00 UTC, nicholaschum commented
Please give us some time, I'll check it out when I get home.

2017-05-11 06:01 UTC, nicholaschum requested changes

2017-05-11 06:01 UTC, nicholaschum commented on app/src/main/java/projekt/substratum/common/commands/FileOperations.java
> +                move(source, destination);
So you are checking if things aren't moving by ThemeInterfacer, you will ask the app too? 

This should be impossible to reach as we use the ThemeInterfacer to move files that third party apps cannot move, such as /data/system/theme folder.

2017-05-11 06:01 UTC, nicholaschum commented on app/src/main/java/projekt/substratum/common/commands/FileOperations.java
> +        InputStream inputStream = null;
In Android Studio, does lint complain that these "= null" checks are redundant?

2017-05-11 14:56 UTC, sirmordred commented on app/src/main/java/projekt/substratum/common/commands/FileOperations.java
> +                move(source, destination);
Done

2017-05-11 14:58 UTC, sirmordred commented on app/src/main/java/projekt/substratum/common/commands/FileOperations.java
> +        InputStream inputStream = null;
it didnt give any warning about redundancy of these checks but
i can remove them if you want although

2017-05-16 02:41 UTC, merged