Introduce inline building for Substratum
nicholaschum/substratum pull request #15
Opened 2016-09-28 10:14 UTC by MSF-Jarvis

This patch allows people to simply track the dev branch of substratum and build the app inline with their ROM builds.

use `make Substratum` to generate the APK and install it to `$OUT/system/app/Substratum/Substratum.apk`

Quirks with this include hate from standard ROM builders who may not have Android SDK installed and set up. The generated APK is signed using platform keys and hence will NOT accept updates from the Play Store. Go figure.

No support will be provided by Team Substratum including but not limited to questions asked in the Google Plus community for OMS ROMs using substratum APKs built inline using this patch.

2016-09-28 10:50 UTC, KreAch3R commented
I understand that building inline everything might be fun, but this is not the correct way to build inline (calling .gradlew).

One would need to call all the AOSP sdk libraries and resources and not depend on android studio, using the correct Android makefile syntax. Check other build inline apps in major ROMs to see how this is done.

Then, it's the matter of updates in a still heavily updated apk. Users won't be able to grab the next update unless they remove the apk with TiB or equivalent. They will probably not flash the ROM again after the next substratum update just for substratum.

2016-09-28 10:56 UTC, MSF-Jarvis commented
Having an ANDROID_HOME variable point to a valid SDK installation is all this needs @KreAch3R and as the commit message and pull request summary say, use of this patch is HEAVILY discouraged and it's simply there for the sake of it. I have had a discussion with @nicholaschum about it and all the drawbacks mentioned are what we (mostly him) had raised issues over. I myself am not using this patch for Chikara, fully understand the drawbacks and issues users will have.

2016-09-28 10:57 UTC, MSF-Jarvis commented
And about building inline, I do not think any major ROM has been building gradle based projects inline yet so don't know where to look. Links?

2016-09-28 10:59 UTC, akhilnarang commented
@MSF-Jarvis A couple of ROMs had been building KernelAdiutor inline, they had to fork it, and make huge modifications, and add an additional repo.......

2016-09-28 11:00 UTC, MSF-Jarvis commented
@akhilnarang Well this implementation can work without huge modifications or even forking. A simply copyfile in the manifest to copy this Android.mk over to packages/apps/substratum is enough. Nothing additional needed except of course,the Android SDK

2016-09-28 11:03 UTC, camcory commented
"I myself am not using this patch for Chikara, fully understand the drawbacks and issues users will have."

Then why even introduce this?

2016-09-28 11:04 UTC, akhilnarang commented
@camcory

2016-09-28 11:05 UTC, MSF-Jarvis commented
@camcory Well nicholaschum said it can be here, I don't really care for it to be very honest. If there's issues against having dead and mostly unused code (of course there are) in the repo I will close this pull request.

2016-09-28 11:14 UTC, Surge1223 commented
But the concern is, that if you're going to do it this way, you might as well just download the apk from the playstore and include it as a prebuilt apk.  ANDROID_HOME pointed to a valid SDK defeats the purpose of building inline, the idea is to use the sources in AOSP.  

AOSP envsetup sets up a variable for AOSP's support libs in config.mk 
SUPPORT_LIBRARY_ROOT := frameworks/support
 
so the proper way to include android's support libs would be to reference for example for appcompat:
appcompat_dir := $(SUPPORT_LIBRARY_ROOT)/v7/appcompat/res

then you could reference multiple support libs using something like this:

res_dirs := res $(appcompat_dir) $(cardview_dir) $(recyclerview_dir) $(design_dir)
LOCAL_SRC_FILES := $(call all-java-files-under, src)
LOCAL_RESOURCE_DIR := $(addprefix $(LOCAL_PATH)/, $(res_dirs))

So the usage of the external SDK is defeating the purpose of building inline. Also the manifest wont contain info like the PlatformBuildVersionName etc that gets added by AAPT when apks are build inline.

2016-09-28 11:14 UTC, KreAch3R commented
@MSF-Jarvis you can't find gradle based inline commits because this is not the way to do it.

[This](https://github.com/CyanogenMod/android_packages_apps_Messaging/blob/cm-13.0/Android.mk) is the way to do it. 
Calling gradlew while you have the whole AOSP setup is bad form.
Creating another dependency in the form of an **external sdk and a correct PATH** while you can even build the sdk (make PRODUCT-sdk-sdk) from AOSP is also a bad idea.

I would support an inline building pull request, just for the sake of the repo being complete, but this needs work.

2016-09-28 11:17 UTC, MSF-Jarvis commented
@Surge1223 Agree to this, @xdevs23 fix your shit dammit, I'm getting hammered here ;) Though how would we able to sync the buttload of gradle dependencies Nick uses on this project is beyond me.

2016-09-28 11:18 UTC, MSF-Jarvis commented
@KreAch3R Closing this for now, too many valid arguments and so little time

2016-09-28 11:22 UTC, xdevs23 commented
There is actually gradle stuff in the aosp tree, but idk if that is usable, building with gradle in aosp is actually not a bad idea... Just actually implementing it in a good way is a little difficult.

2016-09-28 11:36 UTC, KreAch3R commented
@xdevs23 Well look my and @Surge1223 arguments above? And if that's not enough, maybe JBQ himself? https://groups.google.com/forum/#!topic/android-building/dxP0tp0e1MI

Using gradle in AOSP is like trying to use a bicycle while driving a car, you should only try to use one way at a time.

2016-09-28 11:37 UTC, xdevs23 commented
Lol never mind

Am 28.09.2016 1:36 nachm. schrieb "George G." <notifications@github.com>:

> @xdevs23 <https://github.com/xdevs23> Well look my and @Surge1223
> <https://github.com/Surge1223> arguments above? And if that's not enough,
> maybe JBQ himself? https://groups.google.com/forum/#!topic/android-
> building/dxP0tp0e1MI
>
> Using gradle in AOSP is like trying to use a bicycle while driving a car,
> you should only try to use one way at a time.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nicholaschum/substratum/pull/15#issuecomment-250142482>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGowjdAmCjG7LAdIPa3wZVKGce44brdjks5qulEkgaJpZM4KIpOv>
> .
>

2016-09-28 11:38 UTC, msfjarvis commented
@xdevs23 Simão get a better email client dammit

2016-09-28 11:43 UTC, xdevs23 commented
@MSF-Jarvis lol go suck a dick i am lazy af, just replied to the mail :joy:

2016-09-28 11:43 UTC, MSF-Jarvis commented
@xdevs23 Me crie

2016-09-28 11:46 UTC, xdevs23 commented
Y u do dis @MSF-Jarvis

2016-09-28 21:36 UTC, nicholaschum commented
Reopening Pull Request as....

This is an OSS, we should allow users to have the option to do this, and @MSF-Jarvis has worked hard on this commit. I appreciate hard work. 

To the team: We can bring up that inline building is now available, but will not be supported by our team from users. ROM devs will have to keep up or just pull directly from source.

2016-09-28 21:57 UTC, nicholaschum requested changes
This commit will need to be cleaned up by the team. It will not be merged as-is.

2016-09-28 22:07 UTC, KreAch3R commented
We should have an Android.mk, as I said, just for the sake of it. But this one needs work.

And I'm not concerned about the support part, because, imo, the users will just be frustrated they won't be able to update the app, so they will probably abandon the idea. That's gonna be a bigger burden for the ROM devs themselves.

But the makefile should make use of the AOSP, not gradle, that's what we were saying

2016-09-28 22:28 UTC, Surge1223 commented
I think I may be in the minority here,  but to me,  It's not about the desire to build the apk inline,  it's just that being able to use AOSP's source and environment is part of the fun/challenge of doing projects like this.  I mean if it's not,  we might as well just  use autoconf,  ./configure make and make Install in  all dirs.   This kind of reminds me of when people build busybox with glibc instead of bionic.  Yeah,  it's easier,  and works for the most part.  But whenever I see someone clamoring about how they just built the latest bleeding edge busybox with 500 apples,  only to see that it was built using glibc I immediately think "what an idiot,  this guy didn't /couldn't figure out how to solve/fix/add dependencies, and took the easy way out. 

I'm not saying that's what's going on here,  im just saying if youre going to put a lot of work into a project,  you might as well do it right.  How else are we going to learn/advance the communities knowledge if we take shortcuts?  Im not questioning whether this is convenient/works but more questioning why people want want to do it this way.  We know the Android build system is not going anywhere,  Id rather want to work towards a solution that uses that.  Like I said before,  if we're going to just make it this way,  then might as well make it a prebuilt app.

2016-09-29 04:10 UTC, MSF-Jarvis commented
I agree with @Surge1223 actually, doing this with full AOSP is going to be a motherfucking pain in the butt, and fun at the same time. The main issue I see is that the app source's dependencies will have to be built inline (properly without gradle) as static java libraries and then passed to Substratum's Android.mk like we do with the support libs and other apps. The dependencies will have further dependencies and those may have even more, so we're in for a deep, _deep_ dependency hell. Welcome to pre-`apt` Ubuntu

2016-09-29 05:44 UTC, xdevs23 commented
This is actually my implementation, the sample project is here: https://github.com/xdevs23/android_mk_gradle

2016-09-29 05:50 UTC, MSF-Jarvis commented
@xdevs23 the authorship has been retained so everyone most probably knows ;)

2016-09-29 10:57 UTC, xdevs23 commented
@MSF-Jarvis just wanted to make sure that nobody misunderstands

2016-09-30 19:11 UTC, MSF-Jarvis commented
@Surge1223 what about tracking another repo (yuck I know, bear with me) with jars of the dependencies and then do this Android.mk up correctly and add those jars as static dependencies. I know we can compile such jars for usage within the tree, dunno about inclusion of prebuilt jars.

2016-09-30 19:13 UTC, xdevs23 commented
@MSF-Jarvis are you serious?

Am 30.09.2016 9:11 nachm. schrieb "Harsh Shandilya" <
notifications@github.com>:

> @Surge1223 <https://github.com/Surge1223> what about tracking another
> repo (yuck I know, bear with me) with jars of the dependencies and then do
> this Android.mk up correctly and add those jars as static dependencies. I
> know we can compile such jars for usage within the tree, dunno about
> inclusion of prebuilt jars.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nicholaschum/substratum/pull/15#issuecomment-250828496>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGowjVAIRRjHO0dily4TyGSMroWDGa2Sks5qvV7ngaJpZM4KIpOv>
> .
>

2016-09-30 19:14 UTC, MSF-Jarvis commented
@xdevs23 get a fucking decent email client. Yes, I am drunk in weekend fever and absolutely serious about this...._for now_

2016-09-30 19:21 UTC, Surge1223 commented
We don't have to track those them to set up the basic dependencies.  I wrote a quick rough mock up of a minimum Android.mk that you could try to add that to

LOCAL_PATH:= $(call my-dir)

SUPPORT_LIBRARY_ROOT := frameworks/support

support_v7  	:= $(SUPPORT_LIBRARY_ROOT)/v7
support_v4  	:= $(SUPPORT_LIBRARY_ROOT)/v4
support_v14  	:= $(SUPPORT_LIBRARY_ROOT)/v14
support_v13  	:= $(SUPPORT_LIBRARY_ROOT)/v13
preference 		:= $(support_v14)/preference
appcompat 		:= $(support_v7)/appcompat
palette  		:= $(support_v7)/palette
cardview 		:= $(support_v7)/cardview/
recyclerview 	:= $(support_v7)/recyclerview
design  		:= $(SUPPORT_LIBRARY_ROOT)/design

include $(CLEAR_VARS)

LOCAL_PACKAGE_NAME := Substratum
LOCAL_CERTIFICATE := platform
LOCAL_PRIVILEGED_MODULE := true
LOCAL_PROGUARD_ENABLED := disabled

LOCAL_SRC_FILES := $(call all-java-files-under, src)
LOCAL_RESOURCE_DIR := \
$(appcompat)/res \
	$(cardview)/res \
	$(recyclerview)/res \
	$(design)/res \
	
LOCAL_STATIC_JAVA_LIBRARIES := \
    android-common \
    android-support-v13 \
    android-support-v4 \
    android-support-v7-appcompat \
    android-support-v7-cardview \
    android-support-v7-recyclerview \
    android-support-design 

LOCAL_AAPT_FLAGS := \
    --auto-add-overlay \
    --extra-packages android.support.v7.appcompat \
    --extra-packages android.support.v7.cardview \
    --extra-packages android.support.v7.recyclerview \
    --extra-packages android.support.design \

include $(BUILD_PACKAGE)

include $(CLEAR_VARS)

LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES := \
	kellinwood-logging-android-1.4:lib/kellinwood-logging-android-1.4.jar \
	substrate:lib/substrate.aar\
	zipsigner-lib-1.17:lib/zipsigner-lib-1.17.jar \
	kellinwood-logging-lib-1.1:lib/kellinwood-logging-lib-1.1.jar \
	zip4j_1.3.2:lib/zip4j_1.3.2.jar \
	kellinwood-logging-log4j-1.0:lib/kellinwood-logging-log4j-1.0.jar \
	zipio-lib-1.8:lib/zipio-lib-1.8.jar

include $(BUILD_MULTI_PREBUILT)

2016-09-30 19:25 UTC, MSF-Jarvis commented
@Surge1223 LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES, this was the one I was looking for. Yours looks close to what I had planned, without the aapt flags tho (I iz noob on that). Will need to assess the feasibility of using jars than gradle dependencies though.

2016-09-30 19:57 UTC, KreAch3R commented
@MSF-Jarvis About the feasibility of manually updating the jars to the correct version: Yes, you are right, and you're starting to grasp the hell that is inline building. :/

2016-09-30 19:59 UTC, MSF-Jarvis commented
However much @nicholaschum appreciates hard work, this is going to be harder than a mountain AND an ongoing task as long as substratum is worked on. Too much work for almost no benefits, as I see it right now. What say @KreAch3R?

2016-09-30 20:05 UTC, KreAch3R commented
@MSF-Jarvis Now you're just saying what's in my head :P This was exactly what I had in mind when I talked about minimum usefulness while a huge task, in an app that gets updated all the time.

Personally, this is also the reason I don't spend time trying to fix this, while I also appreciate every contribution that is made, and I want to help. 

I don't want to decide on this on my own, though. If anyone of you or a future dev wants, he/she can tackle this. It will only make this repo more complete. 

But besides a proof of concept, it serves very little purpose for me.

2016-09-30 20:09 UTC, MSF-Jarvis commented
@KreAch3R if we behave like lazy fucks and go ahead with hax (both are strict no-no's though), we can merge this as is but as you said in the first place, using gradle within an AOSP tree is bad, plus we're introducing the Android SDK and PATH extension dependencues too. This patch is kinda hopeless as it stands now. Let's just wait it out for someone desperate enough to fix this up and do it right. You and me are not those guys ;)

2016-09-30 20:26 UTC, MSF-Jarvis commented
And this marks the probable end of the longest discussion on any of my pull requests :laughing:

2016-10-01 09:18 UTC, xdevs23 commented
well, i guess the sdk is included in the aosp tree.

2016-10-08 09:20 UTC, xdevs23 commented
Do you even build android.mk on travis :thinking:

2016-10-08 09:26 UTC, MSF-Jarvis commented
Woops, was just testing if @nicholaschum was right about travis builds failing because of his dependencies. Fuck no he wasn't, it builds all right https://travis-ci.org/MSF-Jarvis/substratum/builds/166015680

2016-10-08 22:21 UTC, nicholaschum commented
@MSF-Jarvis your first build succeeded while your latest commit failed. Anyways, this conversation is now locked since the topic has been completely strayed off.

2016-10-08 22:21 UTC, closed without merging